
[General]
	# Provides more output to the log. Mostly used for development and debugging.
	Debug = false
	# Resets the player's progress after death.
	Hardcore = false

[Health]
	# The amount of half-hearts a user will have in a new game and after death.
	#Range: 1 ~ 127
	"Default Health" = 20
	# The maximum amount of half-hearts a user can have.
	#Range: -1 ~ 32767
	"Maximum Health" = -1
	# The levels at which the user will gain a heart.
	"Level Ramp" = [1, 5, 10, 15, 20, 25, 30, 34, 38, 42, 46, 50, 53, 56, 59, 62, 64, 66, 68, 70, 75, 80, 85, 90, 95, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]

[Gui]
	# Whether or not to use the custom HUD provided by LevelHearts. Only disable if you're having mod conflicts.
	"LevelHearts HUD" = true
	# Changes the HUD to display health in one-row only.
	"LevelHearts Minimal HUD" = false

[Xp]
	#How much to multiply the value of XP by.
	#Range: 0.0 ~ 127.0
	"XP Multiplier" = 1.0
	#Force players to lose their XP even if keepInventory is enabled.
	"Always Lose XP on Death" = false

